import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fish Crew',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout: React.FC <Props> = ({ children } ) => {
  return (
    <html lang="fr">
      <head />
      <body>
          {children}
      </body>
    </html>
  )
}
export default RootLayout
